[project]
name = "cartola-scheduling-agent"
version = "0.1.0"
description = "Cartola's scheduling agent for the A2A project."
requires-python = ">=3.10"
dependencies = [
    "a2a-sdk>=0.2.5",
    "google-adk>=1.2.1",
    "python-dotenv",
    "uvicorn",
    "litellm>=1.77.1",
] 
